import React, { useState } from 'react';
import { addActivity, getActivities } from './ActivityService';

const CreateActivity = () => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [startDate, setStartDate] = useState('');
  const [startTime, setStartTime] = useState('');
  const [endTime, setEndTime] = useState('');
  const [isRecurring, setIsRecurring] = useState(false);
  const [recurrenceFrequency, setRecurrenceFrequency] = useState('Weekly');
  const [recurrenceEndDate, setRecurrenceEndDate] = useState('');
  const [isDraft, setIsDraft] = useState(false);
  const [successMsg, setSuccessMsg] = useState('');
  const [errorMsg, setErrorMsg] = useState('');

  // Lokations-håndtering
  const [locations, setLocations] = useState([
    { locationId: 1, startTime: '', endTime: '' }
  ]);

  const handleLocationChange = (index, field, value) => {
    const newLocations = [...locations];
    newLocations[index][field] = value;
    setLocations(newLocations);
  };

  const addLocation = () => {
    setLocations([...locations, { locationId: 1, startTime: '', endTime: '' }]);
  };

  const removeLocation = (index) => {
    if (locations.length > 1) {
      const newLocations = locations.filter((_, i) => i !== index);
      setLocations(newLocations);
    }
  };

   const handleSubmit = async (e) => {
    e.preventDefault();
    setSuccessMsg('');
    setErrorMsg('');

    // Auto-detect draft if essential fields missing
    const autoDraft = !startDate || !startTime || !endTime || locations.length === 0 || !locations.some(loc => loc.locationId);
    const draftToSave = isDraft || autoDraft;

    try {
      // Byg StartTime og EndTime for hovedeventet (kun hvis ikke draft)
      const startDateTime = startDate ? `${startDate}T${startTime}` : null;
      const endDateTime = startDate ? `${startDate}T${endTime}` : null;

      // Byg locations-array med fulde datetime
      const locationsPayload = locations
        .filter(loc => loc.locationId) // only include locations with an id
        .map(loc => ({
          LocationId: Number(loc.locationId),
          StartTime: startDate ? `${startDate}T${loc.startTime}` : null,
          EndTime: startDate ? `${startDate}T${loc.endTime}` : null
        }));

      // Call addActivity from ActivityService
      const newActivity = await addActivity({
        title,
        description,
        startDate: startDate || null,
        startTime: startTime || null,
        endTime: endTime || null,
        isRecurring,
        recurrenceFrequency: isRecurring ? recurrenceFrequency : null,
        recurrenceEndDate: isRecurring ? recurrenceEndDate : null,
        occurrences: [], // will be generated by addActivity
        isDraft: draftToSave
      });

      setSuccessMsg(draftToSave ? 'Aktivitet gemt som kladde!' : 'Aktivitet oprettet succesfuldt!');

      // Reset form
      setTitle('');
      setDescription('');
      setStartDate('');
      setStartTime('');
      setEndTime('');
      setIsRecurring(false);
      setRecurrenceEndDate('');
      setIsDraft(false);
      setLocations([{ locationId: 1, startTime: '', endTime: '' }]);

      setTimeout(() => setSuccessMsg(''), 3000);
    } catch (err) {
      setErrorMsg(err.message);
      setTimeout(() => setErrorMsg(''), 5000);
    }
  };

  return (
    <div className="create-activity-container" style={{ padding: '20px' }}>
      <h1>Opret ny aktivitet</h1>
      {successMsg && (
        <div style={{ backgroundColor: '#d4edda', color: '#155724', padding: '10px', borderRadius: '5px', marginBottom: '15px', maxWidth: '400px' }}>
          {successMsg}
        </div>
      )}
      {errorMsg && (
        <div style={{ backgroundColor: '#f8d7da', color: '#721c24', padding: '10px', borderRadius: '5px', marginBottom: '15px', maxWidth: '400px' }}>
          {errorMsg}
        </div>
      )}
      <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', maxWidth: '400px', gap: '15px' }}>
        {/* Grundlæggende felter */}
        <div>
          <label htmlFor="title">Titel</label>
          <input
            type="text"
            id="title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            required
            style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
          />
        </div>
        <div>
          <label htmlFor="description">Beskrivelse</label>
          <textarea
            id="description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            style={{ padding: '8px', marginTop: '5px', minHeight: '100px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
          />
        </div>
        <div>
          <label htmlFor="startDate">Startdato (valgfri for kladde)</label>
          <input
            type="date"
            id="startDate"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
          />
        </div>

        <div style={{ display: 'flex', gap: '15px' }}>
          <div style={{ flex: 1 }}>
            <label htmlFor="startTime">Starttidspunkt (valgfri for kladde)</label>
            <input
              type="time"
              id="startTime"
              value={startTime}
              onChange={(e) => setStartTime(e.target.value)}
              style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
            />
          </div>
          <div style={{ flex: 1 }}>
            <label htmlFor="endTime">Sluttidspunkt (valgfri for kladde)</label>
            <input
              type="time"
              id="endTime"
              value={endTime}
              onChange={(e) => setEndTime(e.target.value)}
              style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
            />
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <input
            type="checkbox"
            id="isDraft"
            checked={isDraft}
            onChange={(e) => setIsDraft(e.target.checked)}
          />
          <label htmlFor="isDraft" style={{ fontWeight: 'bold' }}>Gem som kladde</label>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <input
            type="checkbox"
            id="isRecurring"
            checked={isRecurring}
            onChange={(e) => setIsRecurring(e.target.checked)}
          />
          <label htmlFor="isRecurring" style={{ fontWeight: 'bold' }}>Er dette en fast/gentagende aktivitet?</label>
        </div>

        {isRecurring && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '15px', padding: '15px', backgroundColor: '#f0f4f8', borderRadius: '5px' }}>
            <div>
              <label htmlFor="frequency">Gentagelsesfrekvens</label>
              <select
                id="frequency"
                value={recurrenceFrequency}
                onChange={(e) => setRecurrenceFrequency(e.target.value)}
                style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
              >
                <option value="Daily">Dagligt</option>
                <option value="Weekly">Ugentligt</option>
                <option value="Monthly">Månedligt</option>
              </select>
            </div>
            <div>
              <label htmlFor="recurrenceEndDate">Slutdato for serien</label>
              <input
                type="date"
                id="recurrenceEndDate"
                value={recurrenceEndDate}
                onChange={(e) => setRecurrenceEndDate(e.target.value)}
                required={isRecurring}
                style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
              />
            </div>
          </div>
        )}

        {/* Lokationer */}
        <div style={{ marginTop: '10px' }}>
          <label style={{ fontWeight: 'bold' }}>Lokationer (valgfri for kladde)</label>
          {locations.map((loc, index) => (
            <div key={index} style={{ display: 'flex', gap: '10px', marginTop: '10px', alignItems: 'flex-end' }}>
              <div style={{ flex: 1 }}>
                <label htmlFor={`loc-id-${index}`}>Lokation</label>
                <select
                  id={`loc-id-${index}`}
                  value={loc.locationId}
                  onChange={(e) => handleLocationChange(index, 'locationId', Number(e.target.value))}
                  style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
                >
                  <option value={0}>Vælg...</option>
                  <option value={1}>Hal A</option>
                  <option value={2}>Hal B</option>
                  <option value={3}>Fitness</option>
                  <option value={4}>Sprog</option>
                </select>
              </div>
              <div style={{ flex: 1 }}>
                <label htmlFor={`loc-start-${index}`}>Starttid</label>
                <input
                  type="time"
                  id={`loc-start-${index}`}
                  value={loc.startTime}
                  onChange={(e) => handleLocationChange(index, 'startTime', e.target.value)}
                  style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
                />
              </div>
              <div style={{ flex: 1 }}>
                <label htmlFor={`loc-end-${index}`}>Sluttid</label>
                <input
                  type="time"
                  id={`loc-end-${index}`}
                  value={loc.endTime}
                  onChange={(e) => handleLocationChange(index, 'endTime', e.target.value)}
                  style={{ padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', width: '100%' }}
                />
              </div>
              {locations.length > 1 && (
                <button type="button" onClick={() => removeLocation(index)} style={{ padding: '8px 12px', backgroundColor: '#dc3545', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', marginTop: '20px' }}>
                  Fjern
                </button>
              )}
            </div>
          ))}
          <button type="button" onClick={addLocation} style={{ marginTop: '10px', padding: '6px 10px', backgroundColor: '#28a745', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
            Tilføj lokation
          </button>
        </div>

        <button type="submit" style={{ marginTop: '10px', padding: '10px', backgroundColor: '#0056b3', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}>
          {isDraft ? 'Gem kladde' : 'Opret Aktivitet'}
        </button>
      </form>
    </div>
  );
};

export default CreateActivity;
