-- Core employee, role, shift, and location schema.

create table if not exists public.employees (
    employee_id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    email text unique,
    phone text,
    birthday date,
    supabase_user_id uuid unique,
    app_access text not null default 'employee' check (app_access in ('admin', 'employee'))
);

create table if not exists public.roles (
    role_id bigint generated by default as identity primary key,
    name text not null unique,
    color text not null default '--color-andet'
);

create table if not exists public.employee_roles (
    employee_id bigint not null references public.employees(employee_id) on delete cascade,
    role_id bigint not null references public.roles(role_id) on delete restrict,
    primary key (employee_id, role_id)
);

create table if not exists public.qualifications (
    qualification_id bigint generated by default as identity primary key,
    name text not null unique,
    description text
);

create table if not exists public.employee_qualifications (
    employee_id bigint not null references public.employees(employee_id) on delete cascade,
    qualification_id bigint not null references public.qualifications(qualification_id) on delete restrict,
    primary key (employee_id, qualification_id)
);

create table if not exists public.shift_categories (
    shiftcategory_id bigint generated by default as identity primary key,
    name text not null unique,
    color text not null default '#94a3b8'
);

create table if not exists public.locations (
    location_id bigint generated by default as identity primary key,
    name text not null unique
);

create table if not exists public.shifts (
    shift_id bigint generated by default as identity primary key,
    start_time timestamp without time zone not null,
    end_time timestamp without time zone not null,
    employee_id bigint references public.employees(employee_id) on delete set null,
    shiftcategory_id bigint not null references public.shift_categories(shiftcategory_id) on delete restrict,
    check (end_time > start_time)
);

create index if not exists idx_employees_supabase_user_id on public.employees(supabase_user_id);
create index if not exists idx_shifts_employee_id on public.shifts(employee_id);
create index if not exists idx_shifts_start_time on public.shifts(start_time);
