-- Event and activity schema.

create table if not exists public.association (
    association_id bigint generated by default as identity primary key,
    name text not null unique,
    website_url text,
    color text,
    logo text
);

create table if not exists public.event_series (
    eventseries_id bigint generated by default as identity primary key,
    name text not null,
    description text,
    category text not null default 'ANDET',
    location_id bigint references public.locations(location_id) on delete set null,
    association_id bigint references public.association(association_id) on delete set null,
    template_id bigint,
    created_at timestamp with time zone not null default now(),
    created_by text not null default ''
);

create table if not exists public.events (
    event_id bigint generated by default as identity primary key,
    name text not null,
    description text,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    date date,
    category text not null default 'ANDET',
    eventseries_id bigint references public.event_series(eventseries_id) on delete set null,
    location_id bigint references public.locations(location_id) on delete set null,
    association_id bigint references public.association(association_id) on delete set null,
    is_modified_from_series boolean not null default false,
    is_cancelled boolean not null default false,
    is_draft boolean not null default false,
    template_id bigint,
    check (end_time is null or start_time is null or end_time > start_time)
);

create table if not exists public.event_locations (
    eventlocations_id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(event_id) on delete cascade,
    location_id bigint references public.locations(location_id) on delete set null,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    date date,
    check (end_time is null or start_time is null or end_time > start_time)
);

create index if not exists idx_events_date on public.events(date);
create index if not exists idx_event_locations_event_id on public.event_locations(event_id);
create index if not exists idx_event_locations_location_id on public.event_locations(location_id);
