-- Contact and association relation schema.

create table if not exists public.contact (
    contact_id bigint generated by default as identity primary key,
    name text not null,
    title text,
    profile_image_url text,
    phone text,
    email text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table if not exists public.association_contact (
    association_id bigint not null references public.association(association_id) on delete cascade,
    contact_id bigint not null references public.contact(contact_id) on delete cascade,
    primary key (association_id, contact_id)
);

create table if not exists public.event_contact (
    event_id bigint not null references public.events(event_id) on delete cascade,
    contact_id bigint not null references public.contact(contact_id) on delete cascade,
    primary key (event_id, contact_id)
);

create index if not exists idx_contact_name on public.contact(name);
create index if not exists idx_contact_email on public.contact(email);
