-- Swap request schema.

create table if not exists public.swap_status (
    swap_status_id bigint generated by default as identity primary key,
    name text not null unique
);

create table if not exists public.swap_requests (
    swap_request_id bigint generated by default as identity primary key,
    requester_id bigint not null references public.employees(employee_id) on delete cascade,
    target_employee_id bigint not null references public.employees(employee_id) on delete cascade,
    offered_shift_id bigint not null references public.shifts(shift_id) on delete cascade,
    requested_shift_id bigint not null references public.shifts(shift_id) on delete cascade,
    swap_status_id bigint references public.swap_status(swap_status_id) on delete restrict,
    created_at timestamp with time zone not null default now(),
    check (requester_id <> target_employee_id),
    check (offered_shift_id <> requested_shift_id)
);

create index if not exists idx_swap_requests_requester_id on public.swap_requests(requester_id);
create index if not exists idx_swap_requests_target_employee_id on public.swap_requests(target_employee_id);
